const START_WORDS=[{ko:'안녕하세요',roman:'annyeonghaseyo',meaning:'hello',mistakes:0},{ko:'감사합니다',roman:'gamsahamnida',meaning:'thank you',mistakes:0},{ko:'네',roman:'ne',meaning:'yes',mistakes:0},{ko:'아니요',roman:'aniyo',meaning:'no',mistakes:0},{ko:'주세요',roman:'juseyo',meaning:'please give me',mistakes:0}];
const phraseTopics={Greetings:'greetings', 'Introduce yourself':'introducing yourself','Ordering food and drinks':'ordering food and drinks','Shopping and prices':'shopping and prices','Asking for directions':'asking for directions','In class':'classroom Korean','Getting around':'getting around by taxi, bus, or subway','Asking for help':'asking for help'};
const state={keys:{gemini:localStorage.getItem('koreanGeminiKey')||'',eleven:localStorage.getItem('koreanElevenKey')||''},words:JSON.parse(localStorage.getItem('koreanWords')||'null')||START_WORDS,chat:[],rules:'',voicesReady:false,recording:null,mediaRecorder:null,audioChunks:[],playing:null,audioCache:{}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function persist(){localStorage.setItem('koreanWords',JSON.stringify(state.words));$('#progressCount').textContent=state.words.length;const wrong=state.words.reduce((n,w)=>n+(w.mistakes||0),0);$('#wrongBadge').textContent=wrong;$('#wrongBadge').hidden=!wrong}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
function setSection(name){$$('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.section===name));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===name));if(name==='words')renderWords()}
function saveKeys(){state.keys.gemini=$('#geminiKey').value.trim();state.keys.eleven=$('#elevenKey').value.trim();localStorage.setItem('koreanGeminiKey',state.keys.gemini);localStorage.setItem('koreanElevenKey',state.keys.eleven);$('#keyNote').textContent='Saved in this browser.';setTimeout(closeKeys,600)}
function openKeys(){$('#geminiKey').value=state.keys.gemini;$('#elevenKey').value=state.keys.eleven;$('#keysModal').hidden=false}function closeKeys(){$('#keysModal').hidden=true}
function showKorean(text){const roman=$('#romanizationToggle').checked;const pieces=text.split(/(안녕하세요|감사합니다|주세요|아니요|네|[가-힣]+(?:\s+[가-힣]+)*)/g);return pieces.map(piece=>/^[가-힣]/.test(piece)?`<span class="korean-piece"><span>${piece}${roman?'':''}</span><span class="piece-actions"><button data-sound="${piece}">Listen</button><button data-sound="${piece}" data-slow="true">Slow</button><button data-save="${piece}">+ My words</button></span></span>`:piece).join('')}
function addMessage(role,text,meta=''){const wrap=document.createElement('div');wrap.className=`message ${role}`;wrap.innerHTML=`<div class="avatar">${role==='tutor'?'한':'You'}</div><div class="bubble">${role==='tutor'?showKorean(text):escapeHtml(text)}${meta?`<small class="cutoff-note">${meta}</small>`:''}</div>`;$('#chatMessages').appendChild(wrap);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadRules(){try{state.rules=await fetch('tutor_rules.txt').then(r=>r.text())}catch{state.rules='Follow the nine tutor rules in tutor_rules.txt.'}}
async function gemini(contents,system){if(!state.keys.gemini)throw new Error('NO_KEY');const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${encodeURIComponent(state.keys.gemini)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{thinkingConfig:{thinkingBudget:0},maxOutputTokens:1000}})});if(!res.ok)throw new Error('API');return res.json()}
function replyText(data){const candidate=data.candidates?.[0];return {text:candidate?.content?.parts?.map(p=>p.text||'').join('')||'',cut:candidate?.finishReason==='MAX_TOKENS'} }
async function sendChat(text){addMessage('user',text);state.chat.push({role:'user',parts:[{text}]});$('#chatInput').value='';const typing='Thinking…';addMessage('tutor',typing);const bubble=$('#chatMessages').lastElementChild.querySelector('.bubble');try{const data=await gemini(state.chat,`You are a patient Korean tutor for English-speaking BGSU beginners. Help them learn rather than handing over answers. Return plain text under 100 words. ${state.rules}`);const result=replyText(data);state.chat.push({role:'model',parts:[{text:result.text}]});bubble.innerHTML=showKorean(result.text)+(result.cut?'<small class="cutoff-note">This reply was cut off. Ask me to continue.</small>':'')}catch(error){bubble.textContent=error.message==='NO_KEY'?'Add your Gemini key in Keys to chat with your tutor.':'I could not reach Gemini this time. Please check your key or try again.'}}
function renderWords(){persist();$('#wordsGrid').innerHTML=state.words.map((word,i)=>`<article class="word-card ${(word.mistakes||0)>0?'missed':''}"><div class="word-card-top"><div><div class="word-korean">${word.ko}</div><div class="word-roman">${word.roman}</div><div class="word-meaning">${word.meaning}</div></div>${word.mistakes?`<span class="mistakes">${word.mistakes} missed</span>`:''}</div><div class="word-actions"><button data-word-sound="${i}">◉ Listen</button><button data-word-sound="${i}" data-word-slow="true">◌ Slow</button><button data-record-word="${i}">● Record</button></div><form class="spell-form" data-spell="${i}"><label>Type it in English letters</label><div class="spell-line"><input aria-label="Romanization for ${word.ko}" autocomplete="off"><button>Check</button></div><div class="spell-result"></div></form></article>`).join('')}
function updateSpeakTarget(){const word=state.words[$('#speakTarget').value||0];if(!word)return;$('#speakKorean').textContent=word.ko;$('#speakRoman').textContent=word.roman;$('#speakMeaning').textContent=word.meaning}
function initSpeak(){ $('#speakTarget').innerHTML=state.words.map((w,i)=>`<option value="${i}">${w.ko} · ${w.meaning}</option>`).join('');updateSpeakTarget()}
function normalize(s){return s.toLowerCase().replace(/[\s-]/g,'')}
function stopSound(){if(state.playing){if(state.playing.pause)state.playing.pause();else speechSynthesis.cancel();state.playing=null}$$('[data-playing]').forEach(b=>{b.textContent=b.dataset.original||b.textContent;b.removeAttribute('data-playing')})}
async function speak(text,slow,button){stopSound();if(button){button.dataset.original=button.textContent;button.textContent='Stop';button.dataset.playing='true'}if(state.keys.eleven){try{const key=`${text}|${slow}`;let url=state.audioCache[key];if(!url){const res=await fetch('https://api.elevenlabs.io/v1/text-to-speech/EXAVITQu4vr4xnSDxMaL',{method:'POST',headers:{'xi-api-key':state.keys.eleven,'Content-Type':'application/json','Accept':'audio/mpeg'},body:JSON.stringify({text,model_id:'eleven_multilingual_v2',voice_settings:{stability:.5,similarity_boost:.75,speed:slow?.65:1}})});if(!res.ok)throw Error();url=URL.createObjectURL(await res.blob());state.audioCache[key]=url}const audio=new Audio(url);state.playing=audio;audio.onended=()=>stopSound();await audio.play();return}catch{toast('Natural voice is unavailable; using your computer voice.')}}await speechReady();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=slow?.62:0.95;u.onend=()=>stopSound();state.playing=u;speechSynthesis.speak(u)}
function speechReady(){return new Promise(resolve=>{if(speechSynthesis.getVoices().length){state.voicesReady=true;resolve();return}speechSynthesis.onvoiceschanged=()=>{state.voicesReady=true;resolve()};setTimeout(resolve,800)})}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia){toast('Microphone is not available here. Open this page in Chrome.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.audioChunks=[];state.mediaRecorder=new MediaRecorder(stream);state.mediaRecorder.ondataavailable=e=>{if(e.data.size)state.audioChunks.push(e.data)};state.mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());checkPronunciation(new Blob(state.audioChunks,{type:'audio/webm'}))};state.mediaRecorder.start();$('#recordButton').innerHTML='<span>■</span> Stop';$('#recordButton').classList.add('recording');$('#recordTitle').textContent='Recording… click Stop when you are done';$('#recordMessage').textContent='Say the target clearly, then stop.'}catch{$('#recordTitle').textContent='Microphone blocked';$('#recordMessage').textContent='Allow microphone access in Chrome, then try again.'}}
function stopRecording(){state.mediaRecorder?.stop();$('#recordButton').disabled=true;$('#recordButton').textContent='Checking…';$('#recordTitle').textContent='Checking your pronunciation…'}
async function checkPronunciation(blob){const target=state.words[$('#speakTarget').value||0];if(blob.size<1500){showFeedback(null,'The recording was too quiet or empty. Try speaking closer to the microphone.');return}try{const buffer=await blob.arrayBuffer();const base64=btoa(String.fromCharCode(...new Uint8Array(buffer)));const data=await gemini([{role:'user',parts:[{text:`Listen to this student's Korean pronunciation. Target: ${target.ko}; English letters: ${target.roman}; meaning: ${target.meaning}. Answer ONLY valid JSON with keys score (whole number 0-5), headline, right, sound, fix, tip.`},{inlineData:{mimeType:'audio/webm',data:base64}}]}],'You are a careful Korean pronunciation coach. Evaluate the supplied audio honestly and kindly.');const result=replyText(data);if(!result.text){showFeedback(null,'No score this time, please try again.');return}const parsed=JSON.parse(result.text.replace(/```json|```/g,''));showFeedback(parsed)}catch(error){showFeedback(null,error.message==='NO_KEY'?'Add your Gemini key in Keys, then try again.':'Gemini could not check that recording. Please try again.')}}
function showFeedback(data,message){const box=$('#pronunciationFeedback');box.hidden=false;$('#recordButton').disabled=false;$('#recordButton').innerHTML='<span>●</span> Record';$('#recordButton').classList.remove('recording');$('#recordTitle').textContent='Ready for another try';$('#recordMessage').textContent=message||'Nice work. Try again and listen for the details.';box.innerHTML=data?`<div class="score-row"><div class="score">${data.score}<small>/5</small></div><strong>${escapeHtml(data.headline)}</strong></div><div class="feedback-section"><h4>What was right</h4><p>${escapeHtml(data.right)}</p></div><div class="feedback-section"><h4>Sound to notice</h4><p>${escapeHtml(data.sound)}</p></div><div class="feedback-section"><h4>How to fix it</h4><p>${escapeHtml(data.fix)}</p></div><div class="feedback-section"><h4>One tip</h4><p>${escapeHtml(data.tip)}</p></div><button class="outline-button" id="tryAgain">Try again</button>`:`<p>${escapeHtml(message||'No score this time, please try again.')}</p>`;$('#tryAgain')?.addEventListener('click',()=>{$('#pronunciationFeedback').hidden=true})}
$$('.nav-tab').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.section)));$('#keysButton').addEventListener('click',openKeys);$('#closeKeys').addEventListener('click',closeKeys);$('#saveKeys').addEventListener('click',saveKeys);$('#forgetKeys').addEventListener('click',()=>{localStorage.removeItem('koreanGeminiKey');localStorage.removeItem('koreanElevenKey');state.keys={gemini:'',eleven:''};$('#geminiKey').value='';$('#elevenKey').value='';$('#keyNote').textContent='Keys forgotten from this browser.'});
$$('.mode-button').forEach(b=>b.addEventListener('click',()=>{const mode=b.dataset.mode;const prompts={letters:'Let us learn three Hangul letters for a complete beginner.',teach:'Teach me one small Korean lesson.',quiz:'Quiz me with the first question.',phrases:'Let us practice an everyday situation.'};if(mode==='phrases'){$('#phraseRow').hidden=false;$('#phraseRow').innerHTML=Object.keys(phraseTopics).map(x=>`<button data-topic="${x}">${x}</button>`).join('');$$('[data-topic]').forEach(x=>x.addEventListener('click',()=>sendChat(`I want to practice ${x}.`)))}else sendChat(prompts[mode])}));$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const text=$('#chatInput').value.trim();if(text)sendChat(text)});document.addEventListener('click',e=>{const sound=e.target.closest('[data-sound]');if(sound)speak(sound.dataset.sound,sound.dataset.slow==='true',sound);const save=e.target.closest('[data-save]');if(save){const ko=save.dataset.save;const found=state.words.find(w=>w.ko===ko);if(!found){state.words.push({ko,roman:'',meaning:'Saved from your tutor',mistakes:0});persist();toast('Saved to My words.')}else toast('That word is already saved.')}const wordSound=e.target.closest('[data-word-sound]');if(wordSound){const word=state.words[wordSound.dataset.wordSound];speak(word.ko,wordSound.dataset.wordSlow==='true',wordSound)}const wordRecord=e.target.closest('[data-record-word]');if(wordRecord){$('#speakTarget').value=wordRecord.dataset.recordWord;updateSpeakTarget();setSection('speak');startRecording()}});
$('#speakTarget').addEventListener('change',updateSpeakTarget);$$('.listen-button,.slow-button').forEach(b=>b.addEventListener('click',()=>{const t=state.words[$('#speakTarget').value||0];speak(t.ko,b.classList.contains('slow-button'),b)}));$('#recordButton').addEventListener('click',()=>state.mediaRecorder?stopRecording():startRecording());$('#reviewButton').addEventListener('click',()=>{const hardest=[...state.words].sort((a,b)=>(b.mistakes||0)-(a.mistakes||0))[0];setSection('tutor');sendChat(`Review my word ${hardest?.ko||'words'} with one four-choice question.`)});
document.addEventListener('submit',e=>{if(!e.target.matches('[data-spell]'))return;e.preventDefault();const i=e.target.dataset.spell,w=state.words[i],input=e.target.querySelector('input'),result=e.target.querySelector('.spell-result');if(normalize(input.value)===normalize(w.roman)){result.textContent='Correct. Nice spelling!';result.className='spell-result good'}else{w.mistakes=(w.mistakes||0)+1;persist();result.textContent='Check the part that differs from the English letters above.';result.className='spell-result bad'}});
loadRules();persist();initSpeak();speechReady();if(!state.keys.gemini)setTimeout(openKeys,500);addMessage('tutor','안녕하세요! I am your Korean tutor. Choose Letters, Teach me, Everyday phrases, or Quiz me to begin.');
